name: Java Maven CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - run: pwd
      - uses: actions/checkout@v3
        with:
          repository: steos/jnafilechooser
          path: './jnafilechooser'
      - run: 'cd ./jnafilechooser'
      - run: pwd
      - run: mvn clean install
      - run: cd ..
      - run: pwd
      - run: mvn clean install
