name: Java Maven CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'

      - uses: actions/checkout@v3
        with:
          repository: steos/jnafilechooser
          path: './jnafilechooser'
      - working-directory: './jnafilechooser'
        run: git checkout f512011434d47489554554aebaced865f5e72179
      - working-directory: './jnafilechooser'
        run: mvn clean install

      - run: mvn clean install
